// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxUaLJcrevtkA2NkSDVWBFlT0lxK-o98',
    appId: '1:811226708856:web:140eb67041d9fd00cfe68d',
    messagingSenderId: '811226708856',
    projectId: 'iot2-5fba7',
    authDomain: 'iot2-5fba7.firebaseapp.com',
    databaseURL: 'https://iot2-5fba7-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-5fba7.appspot.com',
    measurementId: 'G-3KXYE2BT6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGYvb2ZWLuq9dmYoQZKYsOsoYSjq2VsE',
    appId: '1:811226708856:android:7ebdd23b6cc41ba5cfe68d',
    messagingSenderId: '811226708856',
    projectId: 'iot2-5fba7',
    databaseURL: 'https://iot2-5fba7-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-5fba7.appspot.com',
  );
}
